### PR TITLE
Reproduce the hanging bug on Github Actions Ubuntu runner

### PR DESCRIPTION
**Pull request by nikita-volkov**
This PR provides a reproduction of the issue. It contains an application that executes two requests: one sends 1K of data, another - 30K. It also contains a Github Actions workflow, which executes it on all available platforms.

As [the workflow execution report](https://github.com/nikita-volkov/hs-connection/actions/runs/2888282880) shows, the app runs fine on all platforms but Ubuntu. On Ubuntu the 1K request runs fine as well, but the 30K request times out. It also seems that this behaviour depends on the host, hence I'm using a specific one there.

This issue has to be hidden somewhere in this library, because I've tested similar interactions using `curl` and there is no problem.

In my practice similar issues appear when output buffers are not getting properly flushed.

### CODE REVIEW

**Comment by mulderr** [comment]
Have you encountered the issue outside of Github Actions? If so can you provide more info about the environment? I am not able reproduce this on my linux machine nor inside a fresh Ubuntu 20.04 VM.

**Comment by nikita-volkov** [comment]
I haven't been able to reproduce this locally either. The issue reproduces specifically on Github Actions and on the Ubuntu runner. There's no issue on macOS and Windows runners. Also this has something to do with the host as well, because it only appears on particular hosts like the one in this PR.

**Comment by mulderr** [comment]
[Here](https://github.com/actions/runner-images/issues/4700) is a very similar issue. The problem was supposedly positively verified by Azure support but the root cause was never identified. Looks to me it's just as likely to be an issue on GH side.

**Comment by nikita-volkov** [comment]
There definitely is a history of related issues of Github itself. E.g., here's another one: https://github.com/actions/runner-images/issues/1187.

However I've tried issuing a request to the same host using CURL on GH Actions and it works fine. Also issuing a request with a smaller body does work with "hs-connection". (The code in this PR and [the execution logs](https://github.com/nikita-volkov/hs-connection/runs/7914973435?check_suite_focus=true) show that).

It's really hard to identify the culprit here. But it seems like somebody with a deeper knowledge of this library may be able to identify the issue better or maybe even fix it (if it's at all fixable on the Haskell end).

**Comment by mulderr** [comment]
I've [set up a script](https://github.com/mulderr/hs-connection/runs/7941755431?check_suite_focus=true) that runs `stack test` three times in a row with 1s delay between runs while also running tcpdump in the background. The results for 30k test is always the same. Below with comments.

```
# 3-way handshake
21:20:45.902762 IP 10.1.1.153.43688 > 84.201.185.129.443: Flags [S], seq 3467862237, win 64240, options [mss 1460,sackOK,TS val 3973009155 ecr 0,nop,wscale 7], length 0
21:20:46.090114 IP 84.201.185.129.443 > 10.1.1.153.43688: Flags [S.], seq 4136951908, ack 3467862238, win 43440, options [mss 1460,sackOK,TS val 736373262 ecr 3973009155,nop,wscale 8], length 0
21:20:46.090162 IP 10.1.1.153.43688 > 84.201.185.129.443: Flags [.], ack 1, win 502, options [nop,nop,TS val 3973009343 ecr 736373262], length 0

# TLS
21:20:46.090576 IP 10.1.1.153.43688 > 84.201.185.129.443: Flags [P.], seq 1:323, ack 1, win 502, options [nop,nop,TS val 3973009343 ecr 736373262], length 322
21:20:46.277276 IP 84.201.185.129.443 > 10.1.1.153.43688: Flags [.], ack 323, win 169, options [nop,nop,TS val 736373450 ecr 3973009343], length 0
21:20:46.279108 IP 84.201.185.129.443 > 10.1.1.153.43688: Flags [P.], seq 1:2857, ack 323, win 169, options [nop,nop,TS val 736373452 ecr 3973009343], length 2856
21:20:46.279108 IP 84.201.185.129.443 > 10.1.1.153.43688: Flags [P.], seq 2857:3301, ack 323, win 169, options [nop,nop,TS val 736373452 ecr 3973009343], length 444
21:20:46.279124 IP 10.1.1.153.43688 > 84.201.185.129.443: Flags [.], ack 2857, win 496, options [nop,nop,TS val 3973009532 ecr 736373452], length 0
21:20:46.279141 IP 10.1.1.153.43688 > 84.201.185.129.443: Flags [.], ack 3301, win 493, options [nop,nop,TS val 3973009532 ecr 736373452], length 0
21:20:46.305782 IP 10.1.1.153.43688 > 84.201.185.129.443: Flags [P.], seq 323:329, ack 3301, win 501, options [nop,nop,TS val 3973009558 ecr 736373452], length 6

# TLS setup most likely ends somewhere around here, at this point client ACKed everything sent by server

# client trying to send data
21:20:46.306050 IP 10.1.1.153.43688 > 84.201.185.129.443: Flags [.], seq 329:1777, ack 3301, win 501, options [nop,nop,TS val 3973009559 ecr 736373452], length 1448
21:20:46.306052 IP 10.1.1.153.43688 > 84.201.185.129.443: Flags [P.], seq 1777:3225, ack 3301, win 501, options [nop,nop,TS val 3973009559 ecr 736373452], length 1448
21:20:46.306057 IP 10.1.1.153.43688 > 84.201.185.129.443: Flags [.], seq 3225:4673, ack 3301, win 501, options [nop,nop,TS val 3973009559 ecr 736373452], length 1448
21:20:46.306057 IP 10.1.1.153.43688 > 84.201.185.129.443: Flags [P.], seq 4673:6121, ack 3301, win 501, options [nop,nop,TS val 3973009559 ecr 736373452], length 1448
21:20:46.306062 IP 10.1.1.153.43688 > 84.201.185.129.443: Flags [.], seq 6121:7569, ack 3301, win 501, options [nop,nop,TS val 3973009559 ecr 736373452], length 1448
21:20:46.306063 IP 10.1.1.153.43688 > 84.201.185.129.443: Flags [P.], seq 7569:9017, ack 3301, win 501, options [nop,nop,TS val 3973009559 ecr 736373452], length 1448
21:20:46.306067 IP 10.1.1.153.43688 > 84.201.185.129.443: Flags [.], seq 9017:10465, ack 3301, win 501, options [nop,nop,TS val 3973009559 ecr 736373452], length 1448
21:20:46.306068 IP 10.1.1.153.43688 > 84.201.185.129.443: Flags [P.], seq 10465:11913, ack 3301, win 501, options [nop,nop,TS val 3973009559 ecr 736373452], length 1448
21:20:46.306272 IP 10.1.1.153.43688 > 84.201.185.129.443: Flags [.], seq 11913:13361, ack 3301, win 501, options [nop,nop,TS val 3973009559 ecr 736373452], length 1448

# first ACK from server, note 329 corresponds to the last packet before starting to send data
21:20:46.492237 IP 84.201.185.129.443 > 10.1.1.153.43688: Flags [.], ack 329, win 169, options [nop,nop,TS val 736373665 ecr 3973009558], length 0

# client is still hoping to get an ACK
21:20:46.492273 IP 10.1.1.153.43688 > 84.201.185.129.443: Flags [.], seq 13361:14809, ack 3301, win 501, options [nop,nop,TS val 3973009745 ecr 736373665], length 1448
21:20:46.492276 IP 10.1.1.153.43688 > 84.201.185.129.443: Flags [P.], seq 14809:16257, ack 3301, win 501, options [nop,nop,TS val 3973009745 ecr 736373665], length 1448
21:20:46.836737 IP 10.1.1.153.43688 > 84.201.185.129.443: Flags [.], seq 16257:17705, ack 3301, win 501, options [nop,nop,TS val 3973010089 ecr 736373665], length 1448

# retransmission attempts, no ACKs from server
21:20:47.380726 IP 10.1.1.153.43688 > 84.201.185.129.443: Flags [.], seq 329:1777, ack 3301, win 501, options [nop,nop,TS val 3973010633 ecr 736373665], length 1448
21:20:48.436705 IP 10.1.1.153.43688 > 84.201.185.129.443: Flags [.], seq 329:1777, ack 3301, win 501, options [nop,nop,TS val 3973011689 ecr 736373665], length 1448
21:20:50.612734 IP 10.1.1.153.43688 > 84.201.185.129.443: Flags [.], seq 329:1777, ack 3301, win 501, options [nop,nop,TS val 3973013865 ecr 736373665], length 1448
21:20:54.964699 IP 10.1.1.153.43688 > 84.201.185.129.443: Flags [.], seq 329:1777, ack 3301, win 501, options [nop,nop,TS val 3973018217 ecr 736373665], length 1448

# nothing more until timeout
```

This looks like a network issue, firewall issue or some kind of filtering/limiting on the server side. It's not that we're handling the buffers wrong. There just is no data coming through.

**Comment by mulderr** [comment]
[Same](https://github.com/mulderr/hs-connection/runs/7942100995?check_suite_focus=true) over plain text on 80/tcp.

If I had to speculate I'd say it could be some kind of DoS protection - once the remote side sees we're dumping garbage without waiting for a reply it either silently drops the connection or intentionally ACKs extremely slowly to make us waste time. Why this does not happen localy? Could be special rules for known GH actions public IPs or that these IPs triggered some automatic rules.

Anyway, do you also observe timeouts on other hosts that we could test?

--

Also regarding CURL - I think it adds some HTTP headers etc? If so, then that is not quite equivalent. The remote side could treat a valid but weird/large HTTP request quite differently than complete garbage.

I'm not great with CURL but if you can paste the command you used we could compare with tcpdump.

**Comment by nikita-volkov** [comment]
Regarding the CURL script here it is:
```bash
openssl rand -hex 30000 | curl -v --no-progress-meter -X POST --data-binary @- https://apigw.yandexcloud.net
```

Here are the results of running it:
https://github.com/nikita-volkov/hs-connection/actions/runs/2902108203

Regarding other hosts to try. I have a service running on the same platform: d5dse1mp8tvk14hqu5cl.apigw.yandexcloud.net. I don't know of any other, however the issues on GH Actions might be of help. E.g., [in this one](https://github.com/actions/runner-images/issues/1187) people mention `piccolo.link`. Naturally the issue may no longer apply to that one though.

**Comment by mulderr** [comment]
[Here](https://github.com/mulderr/hs-connection/runs/7949312286?check_suite_focus=true) is a another test.

Some conclusions:
* `curl` indeed works
* however, `curl -X POST` sends a valid HTTP/1.1 (in plaintext) or HTTP/2 (over https) request so it's much different than sending random data altogether
* a much better way to recreate the scenario would be using `openssl s_client`

The following command:
```
openssl rand -hex 30000 | time openssl s_client -quiet -connect apigw.yandexcloud.net:443
```
does hang and times out after 2 mins, quite similarly to `stack test`.

Since the behavior can be recreated with `openssl s_client` I think we can rule out a library bug. I'm guessing that wrapping the data in a valid HTTP POST on the Haskell side would make the server produce a response but that seems a pointless exercise at this point.

**Comment by nikita-volkov** [comment]
Needs mentioning, that I've discovered this issue when I was using the http-client lib, which suggests that the issue persists on valid http requests

**Comment by nikita-volkov** [comment]
Thanks for your help in digging into this! 

Do I understand correctly that the likely culprit here is GitHub Actions itself?

**Comment by mulderr** [comment]
I'm not entirely sure but yeah, it does look like it's something in the GH Actions infrastructure or the traffic from GH Actions triggers some special rules on the remote side.

Interesting about `http-client`. If you encounter this outside of GH Actions then it would definitely be worth investigating more. I'll keep an eye out on this as well.

**Pull request closed without merging**
